  Cardiometabolic Risk                          0.2314      (metabolic syndrome)
  Subclinical Atherosclerosis                   N/A         (unresolved)
  Hypertension                                  N/A         (early onset hypertension)
  Dyslipidemia                                  0.0441      (inherited lipid metabolism disorder)
  Alcohol-Associated Liver Disease (ALD)        0.0113      (alcoholic liver diseases)
  Liver Injury                                  0.5865      (liver disorder)
  Alcohol Use Disorder (AUD)                    0.1204      (alcohol dependence)
  Liver Fibrosis                                0.3033      (Hepatic fibrosis)
  chronic kidney disease                        0.4221      (chronic kidney disease)
  Metabolic Bone Disease                        0.6390      (metabolic bone disorder)
  cardiovascular disorder                       0.5781      (cardiovascular disorder)
  Heart Disease                                 0.5781      (cardiovascular disorder)
  Prediabetes                                   0.3851      (prediabetes syndrome)
  Cardiovascular Risk Reduction                 0.5781      (cardiovascular disorder)
  Dysbiosis                                     N/A         (unresolved)
  Type 2 Diabetes Mellitus (Prevention)         0.7607      (type 2 diabetes mellitus)
  hypertriglyceridemia                          0.0486      (hypertriglyceridemia)
  Painful Diabetic Peripheral Neuropathy (PDPN) N/A         (unresolved)
  Metabolic Dysfunction-associated Steatohepatitis (MASH) 0.4140      (metabolic dysfunction-associated steatohepatitis)
  Postmenopause                                 N/A         (unresolved)
  Non-Alcoholic Fatty Liver Disease (NAFLD)     0.5700      (metabolic dysfunction-associated steatotic liver disease)
  Hepatic Impairment                            0.5865      (liver disorder)
  Renal Impairment                              0.0542      (Abnormal renal physiology)
  Diabetic Peripheral Neuropathy (DPN)          0.3187      (diabetic neuropathy)
