📊 Score results:
  Cardiovascular Disease                        0.7329      (cardiovascular disorder)
  Hypertension                                  0.5585      (Hypertension)
  Dyslipidemia                                  0.2674      (inherited lipid metabolism disorder)
  NAFLD                                         0.6945      (metabolic dysfunction-associated steatotic liver disease)
  CV Risk Reduction                             0.6668      (tonsillectomy risk measurement)
  NASH                                          0.5296      (metabolic dysfunction-associated steatohepatitis)
  Prediabetes                                   0.4456      (prediabetes syndrome)  (also: Pre-Diabetes)
  Increased Cardiovascular Risk                 0.6013      (metabolic syndrome)
  Cardiovascular Risk/Disease                   0.6013      (metabolic syndrome)
  MASH                                          0.5296      (metabolic dysfunction-associated steatohepatitis)
  Metabolic Associated Liver Disease (Malo)     0.6945      (malonic aciduria)
  Metabolic Dysfunction-Associated Steatotic Liver Disease (Masld) 0.6945      (metabolic dysfunction-associated steatotic liver disease)
  MACE Reduction                                N/A         (major adverse cardiovascular event measurement)
  Cardiovascular (Cv) Outcomes                  0.7329      (cardiovascular disorder)
  Psoriatic Arthritis                           0.2895      (psoriatic arthritis)
  HFpEF                                         N/A         (unresolved)
